export const AUDIT_ACTIONS = {
  PROFESSIONAL_UPDATED: 'PROFESSIONAL_UPDATED',
  PROTOCOL_DRAFT_CREATED: 'PROTOCOL_DRAFT_CREATED',
  PROTOCOL_DRAFT_EDITED: 'PROTOCOL_DRAFT_EDITED',
  PROTOCOL_PUBLISHED: 'PROTOCOL_PUBLISHED',
  PROTOCOL_RETIRED: 'PROTOCOL_RETIRED',
  PROTOCOL_DEFAULT_CHANGED: 'PROTOCOL_DEFAULT_CHANGED',
  PROTOCOL_AUTOMATION_CHANGED: 'PROTOCOL_AUTOMATION_CHANGED',
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  DOSE_SCHEDULE_EDITED: 'DOSE_SCHEDULE_EDITED',
  DOSE_ADMINISTERED: 'DOSE_ADMINISTERED',
  PROTOCOL_BACKFILLED: 'PROTOCOL_BACKFILLED',
  EMAIL_CHANGE_REQUESTED: 'EMAIL_CHANGE_REQUESTED',
  EMAIL_CHANGE_CONFIRMED: 'EMAIL_CHANGE_CONFIRMED',
  USER_EMAIL_CHANGED: 'USER_EMAIL_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  USER_ARCHIVED: 'USER_ARCHIVED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',

  ROLE_GRANTED: 'ROLE_GRANTED',
  ROLE_REVOKED: 'ROLE_REVOKED',

  PATIENT_UPDATED: 'PATIENT_UPDATED',
  PATIENT_STATUS_CHANGED: 'PATIENT_STATUS_CHANGED',
  PATIENT_ARCHIVED: 'PATIENT_ARCHIVED',
  IMMUNOTHERAPY_UPDATED: 'IMMUNOTHERAPY_UPDATED',
  IMMUNOTHERAPY_STATUS_CHANGED: 'IMMUNOTHERAPY_STATUS_CHANGED',
  IMMUNOTHERAPY_ARCHIVED: 'IMMUNOTHERAPY_ARCHIVED',
  DOSE_STATUS_CHANGED: 'DOSE_STATUS_CHANGED',
  DOSE_ARCHIVED: 'DOSE_ARCHIVED',

  INVITE_CREATED: 'INVITE_CREATED',
  INVITE_CANCELLED: 'INVITE_CANCELLED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ENTITY_TYPES = {
  TREATMENT_PROTOCOL: 'TreatmentProtocol',
  USER: 'User',
  PROFESSIONAL: 'Professional',
  PATIENT: 'Patient',
  IMMUNOTHERAPY: 'Immunotherapy',
  DOSE: 'Dose',
  INTERNAL_USER_INVITE: 'InternalUserInvite',
  ORGANIZATION: 'Organization',
} as const;

export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];

export interface AuditLogQuery {
  entityType?: AuditEntityType;
  entityId?: string;
  userId?: string;
  action?: AuditAction;
  from?: Date;
  to?: Date;
  limit?: number;
  cursor?: string;
}

export interface AuditEntry {
  userId: string;
  organizationId: string;
  entityType: AuditEntityType;
  entityId: string;
  action: AuditAction;
  oldValues?: Record<string, unknown>;
  newValues?: Record<string, unknown>;
  changedFields?: string[];
  sessionId?: string;
}
