export const MAINTENANCE_FIRST_INTERVAL = 14;
export const MAINTENANCE_SECOND_INTERVAL = 21;
export const MAINTENANCE_THIRD_INTERVAL = 28;

export const MAINTENANCE_INTERVALS = [
  { interval: 'FIRST', days: MAINTENANCE_FIRST_INTERVAL },
  { interval: 'SECOND', days: MAINTENANCE_SECOND_INTERVAL },
  { interval: 'THIRD', days: MAINTENANCE_THIRD_INTERVAL },
];
